### ISSUE TITLE
[Epic] Implement the PoC core game loop (frontend)

### ISSUE THREAD

**Issue by norswap** [0xFableOrg/0xFable#24]
So far, I've focused on laying strong foundations in the frontend, but now it's actually time to implement the core game loop that is already implemented and cursorily tested in the contracts.

This simple game loop just consists in the ability of playing creatures and having them attack magic-style: the attacker selects attacking creatures, the defender selects which creatures to block, and which creatures he controls blocks which attacking creatures (only one-on-one blocking).

- [x] https://github.com/norswap/0xFable/issues/6
- [x] https://github.com/norswap/0xFable/issues/25
- [x] https://github.com/norswap/0xFable/issues/26
- [ ] https://github.com/norswap/0xFable/issues/27
- [ ] https://github.com/norswap/0xFable/issues/28

This is the critical path to the tech demo, which I'm likely to tackle myself, but help is nevertheless welcome, especially preparing components and logic that could be used at a later stage. In particular:

- all the logic to scroll in the drawer components (I might skip most of it at first)
     - similarly, smooth scrolling if that turns out to be difficult
- drag-and-drop logic (for playing cards)
- arrow-drag-and-drop-logic (for defending)
- pretty glow effects & other graphical niceties
